### ISSUE TITLE
Infura configuration

### ISSUE THREAD

**Issue by Lakatoi** [aquiladev/ipfs-action#24]
When trying using infura I get the following message:

```
Run aquiladev/ipfs-action@v0.1.3
Error: Service is not supported
(node:1998) UnhandledPromiseRejectionWarning: Error: Service is not supported
    at validate (/home/runner/work/_actions/aquiladev/ipfs-action/v0.1.3/uploader/index.js:15:11)
    at Object.upload (/home/runner/work/_actions/aquiladev/ipfs-action/v0.1.3/uploader/index.js:20:3)
    at run (/home/runner/work/_actions/aquiladev/ipfs-action/v0.1.3/runner.js:29:33)
    at Object.<anonymous> (/home/runner/work/_actions/aquiladev/ipfs-action/v0.1.3/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
(node:1998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aquiladev** [comment]
v0.1.3 does not support Infura, please use version 0.1.4 or above
