### ISSUE TITLE
Error: The user aborted a request.

### ISSUE THREAD

**Issue by alefvanoon** [aquiladev/ipfs-action#25]
```
Error: The user aborted a request.
(node:1809) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.
    at abort (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/node-fetch/lib/index.js:1418:16)
    at AbortSignal.abortAndFinalize (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/node-fetch/lib/index.js:1433:4)
    at AbortSignal.dispatchEvent (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at AbortSignal.onAbort (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/any-signal/index.js:13:16)
    at AbortSignal.dispatchEvent (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at AbortSignal.onAbort (/home/runner/work/_actions/aquiladev/ipfs-action/master/node_modules/any-signal/index.js:13:16)
(node:1809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aquiladev** [comment]
Could you provide code of actions's usage?

**Comment by alefvanoon** [comment]
name: Deploy to GitHub Pages

on:
    push:
        branches:
            - build

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node
              uses: actions/setup-node@v2

            - run: yarn install
            - run: yarn build

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: target
                  fqdn: hydrogen.alefvanoon.xyz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload to Infura
              uses: aquiladev/ipfs-action@master
              id: infura
              with:
                path: ./public
                service: infura
                host: ipfs.infura.io
                port: 5001
                timeout: 120000
                verbose: true
            - name: Update DNSLink
              run: npx dnslink-cloudflare -d alefvanoon.xyz -l /ipfs/${{ steps.ipfs-add.outputs.hash }} -r _dnslink.hydrogen
              env:
                CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

**Comment by aquiladev** [comment]
seems it was a problem on infura side, I ran test pipeline, everything works as expected
https://github.com/aquiladev/dapps-delivery-guide/runs/4362340764?check_suite_focus=true

**Comment by aquiladev** [comment]
#31
